on:
  workflow_call:
    inputs:
      goreleaser_args:
        required: false
        type: string
        default: --snapshot
    secrets:
      SIGNPATH_API_TOKEN:
        required: true

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: linux
            runs-on: ubuntu-latest
          - os: windows
            runs-on: windows-latest
            goreleaser_args: "-p 1" # Wails packaging for windows cannot handle parallel builds
          - os: darwin
            runs-on: macos-latest
            goreleaser_args: "-p 1" # Wails packaging for darwin cannot handle parallel builds
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser ${{ inputs.goreleaser_args }}
        uses: ./.github/actions/goreleaser
        with:
          args: release --split --clean ${{ matrix.platform.goreleaser_args }} ${{ inputs.goreleaser_args }}
        env:
          GGOOS: ${{ matrix.platform.os }}

      - name: Archive artifacts
        id: upload_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform.os }}
          path: dist/**/*

      - name: Sign artifacts
        id: sign_windows
        if: ${{ matrix.platform.os == 'windows' && startsWith(github.ref, 'refs/tags/') }}
        uses: signpath/github-action-submit-signing-request@v1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: 'd1f0888a-08d3-44fe-9da0-6490890e20ea'
          project-slug: 'SatisfactoryModManager'
          signing-policy-slug: 'release-signing'
          github-artifact-id: '${{ steps.upload_artifacts.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: 'dist/signed'

      - name: Archive signed artifacts
        if: ${{ matrix.platform.os == 'windows' && startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform.os }}
          path: dist/signed/**/*
          overwrite: true

  finalize:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup
        with:
          backend: false
          frontend: false

      - name: Download windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-windows
          path: dist

      - name: Download linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-linux
          path: dist

      - name: Download darwin artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-darwin
          path: dist

      - name: Run GoReleaser Merge ${{ inputs.goreleaser_args }}
        uses: ./.github/actions/goreleaser
        with:
          args: continue --merge ${{ inputs.goreleaser_args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-all
          path: dist/**/*