name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    uses: ./.github/workflows/build-base.yml
    with:
      goreleaser_args: ''
    secrets:
      SIGNPATH_API_TOKEN: ${{ secrets.SIGNPATH_API_TOKEN }}
